development:
  adapter: mysql2
  encoding: utf8
  database: doc_development
  username: root
  password: password
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: doc_test
  username: root
  password: password
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: doc_production
  username: root
  password: password
  socket: /tmp/mysql.sock
